# Generated by Django 5.0.6 on 2024-07-06 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_position_alter_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='joinAt',
            field=models.DateField(auto_now_add=True, default=datetime.date(2024, 7, 6)),
            preserve_default=False,
        ),
    ]
